databases:
  - name: lostandfound-db
    plan: free
    databaseName: lostandfound
    user: lostandfound

services:
  - type: web
    name: lostandfound
    plan: free
    runtime: python
    buildCommand: "bash build.sh"
    startCommand: "python manage.py migrate --no-input && gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lostandfound-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: LAN_HOST
        value: ""
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
